[package]
name = "cklein-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
cklein-core = { path = "../cklein-core" }
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.96"

[lib]
proc-macro = true
